/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lejeuloto;

/**
 *
 * @author yannt
 */
public class AjoutLotDlg extends javax.swing.JDialog {

    /**
     * Creates new form AjoutLotDlg
     */
    public AjoutLotDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        North = new javax.swing.JPanel();
        TitreLabel = new javax.swing.JLabel();
        Center = new javax.swing.JPanel();
        HGPanel = new javax.swing.JPanel();
        DescriptifLabel = new javax.swing.JLabel();
        CatLabel = new javax.swing.JLabel();
        NiveauLabel = new javax.swing.JLabel();
        HDPanel = new javax.swing.JPanel();
        DescriptifTF = new javax.swing.JTextField();
        CatPanel = new javax.swing.JPanel();
        BonCadeauRB = new javax.swing.JRadioButton();
        ObjetRB = new javax.swing.JRadioButton();
        NiveauPanel = new javax.swing.JPanel();
        Niveau1RB = new javax.swing.JRadioButton();
        Niveau2RB = new javax.swing.JRadioButton();
        Niveau3RB = new javax.swing.JRadioButton();
        BGPanel = new javax.swing.JPanel();
        BDPanel = new javax.swing.JPanel();
        South = new javax.swing.JPanel();
        AnnulerButton = new javax.swing.JButton();
        ValiderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TitreLabel.setText("Saisie d'un nouveau lot");
        North.add(TitreLabel);

        getContentPane().add(North, java.awt.BorderLayout.NORTH);

        Center.setLayout(new java.awt.GridLayout(2, 2));

        HGPanel.setLayout(new java.awt.GridLayout(3, 1));

        DescriptifLabel.setText("Descriptif");
        HGPanel.add(DescriptifLabel);

        CatLabel.setText("Catégorie");
        HGPanel.add(CatLabel);

        NiveauLabel.setText("Niveau");
        HGPanel.add(NiveauLabel);

        Center.add(HGPanel);

        HDPanel.setLayout(new java.awt.GridLayout(3, 1));
        HDPanel.add(DescriptifTF);

        CatPanel.setLayout(new java.awt.GridLayout(1, 2));

        BonCadeauRB.setText("Bon cadeau");
        CatPanel.add(BonCadeauRB);

        ObjetRB.setText("Objet");
        CatPanel.add(ObjetRB);

        HDPanel.add(CatPanel);

        NiveauPanel.setLayout(new java.awt.GridLayout(1, 3));

        Niveau1RB.setText("1");
        NiveauPanel.add(Niveau1RB);

        Niveau2RB.setText("2");
        NiveauPanel.add(Niveau2RB);

        Niveau3RB.setText("3");
        NiveauPanel.add(Niveau3RB);

        HDPanel.add(NiveauPanel);

        Center.add(HDPanel);

        javax.swing.GroupLayout BGPanelLayout = new javax.swing.GroupLayout(BGPanel);
        BGPanel.setLayout(BGPanelLayout);
        BGPanelLayout.setHorizontalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        BGPanelLayout.setVerticalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        Center.add(BGPanel);

        javax.swing.GroupLayout BDPanelLayout = new javax.swing.GroupLayout(BDPanel);
        BDPanel.setLayout(BDPanelLayout);
        BDPanelLayout.setHorizontalGroup(
            BDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        BDPanelLayout.setVerticalGroup(
            BDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        Center.add(BDPanel);

        getContentPane().add(Center, java.awt.BorderLayout.CENTER);

        South.setLayout(new java.awt.GridLayout(1, 2));

        AnnulerButton.setText("Annuler");
        South.add(AnnulerButton);

        ValiderButton.setText("Valider");
        South.add(ValiderButton);

        getContentPane().add(South, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjoutLotDlg dialog = new AjoutLotDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnulerButton;
    private javax.swing.JPanel BDPanel;
    private javax.swing.JPanel BGPanel;
    private javax.swing.JRadioButton BonCadeauRB;
    private javax.swing.JLabel CatLabel;
    private javax.swing.JPanel CatPanel;
    private javax.swing.JPanel Center;
    private javax.swing.JLabel DescriptifLabel;
    private javax.swing.JTextField DescriptifTF;
    private javax.swing.JPanel HDPanel;
    private javax.swing.JPanel HGPanel;
    private javax.swing.JRadioButton Niveau1RB;
    private javax.swing.JRadioButton Niveau2RB;
    private javax.swing.JRadioButton Niveau3RB;
    private javax.swing.JLabel NiveauLabel;
    private javax.swing.JPanel NiveauPanel;
    private javax.swing.JPanel North;
    private javax.swing.JRadioButton ObjetRB;
    private javax.swing.JPanel South;
    private javax.swing.JLabel TitreLabel;
    private javax.swing.JButton ValiderButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    // End of variables declaration//GEN-END:variables
}
