/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lejeuloto;

import javax.swing.JComboBox;

/**
 *
 * @author yannt
 */
public class AjoutLotDlg extends javax.swing.JDialog {
    private boolean validated;
    private Lot l;
    private int niveau;
    private String type;
    private JComboBox ValeurCB;
    /**
     * Creates new form AjoutLotDlg
     */
    public AjoutLotDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        validated = false;
        niveau = 0;
        type = "";
        ValeurCB = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CatButtonGroup = new javax.swing.ButtonGroup();
        NiveauButtonGroup = new javax.swing.ButtonGroup();
        North = new javax.swing.JPanel();
        TitreLabel = new javax.swing.JLabel();
        Center = new javax.swing.JPanel();
        HGPanel = new javax.swing.JPanel();
        DescriptifLabel = new javax.swing.JLabel();
        CatLabel = new javax.swing.JLabel();
        NiveauLabel = new javax.swing.JLabel();
        HDPanel = new javax.swing.JPanel();
        DescriptifTF = new javax.swing.JTextField();
        CatPanel = new javax.swing.JPanel();
        BonCadeauRB = new javax.swing.JRadioButton();
        ObjetRB = new javax.swing.JRadioButton();
        NiveauPanel = new javax.swing.JPanel();
        Niveau1RB = new javax.swing.JRadioButton();
        Niveau2RB = new javax.swing.JRadioButton();
        Niveau3RB = new javax.swing.JRadioButton();
        BGPanel = new javax.swing.JPanel();
        BDPanel = new javax.swing.JPanel();
        South = new javax.swing.JPanel();
        AnnulerButton = new javax.swing.JButton();
        ValiderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TitreLabel.setText("Saisie d'un nouveau lot");
        North.add(TitreLabel);

        getContentPane().add(North, java.awt.BorderLayout.NORTH);

        Center.setLayout(new java.awt.GridLayout(2, 2));

        HGPanel.setLayout(new java.awt.GridLayout(3, 1));

        DescriptifLabel.setText("Descriptif");
        HGPanel.add(DescriptifLabel);

        CatLabel.setText("Catégorie");
        HGPanel.add(CatLabel);

        NiveauLabel.setText("Niveau");
        HGPanel.add(NiveauLabel);

        Center.add(HGPanel);

        HDPanel.setLayout(new java.awt.GridLayout(3, 1));
        HDPanel.add(DescriptifTF);

        CatPanel.setLayout(new java.awt.GridLayout(1, 2));

        BonCadeauRB.setText("Bon cadeau");
        CatButtonGroup.add(BonCadeauRB);
        BonCadeauRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BonCadeauRBActionPerformed(evt);
            }
        });
        CatPanel.add(BonCadeauRB);

        ObjetRB.setText("Objet");
        CatButtonGroup.add(ObjetRB);
        ObjetRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjetRBActionPerformed(evt);
            }
        });
        CatPanel.add(ObjetRB);

        HDPanel.add(CatPanel);

        NiveauPanel.setLayout(new java.awt.GridLayout(1, 3));

        Niveau1RB.setText("1");
        NiveauButtonGroup.add(Niveau1RB);
        Niveau1RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Niveau1RBActionPerformed(evt);
            }
        });
        NiveauPanel.add(Niveau1RB);

        Niveau2RB.setText("2");
        NiveauButtonGroup.add(Niveau2RB);
        Niveau2RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Niveau2RBActionPerformed(evt);
            }
        });
        NiveauPanel.add(Niveau2RB);

        Niveau3RB.setText("3");
        NiveauButtonGroup.add(Niveau3RB);
        Niveau3RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Niveau3RBActionPerformed(evt);
            }
        });
        NiveauPanel.add(Niveau3RB);

        HDPanel.add(NiveauPanel);

        Center.add(HDPanel);

        javax.swing.GroupLayout BGPanelLayout = new javax.swing.GroupLayout(BGPanel);
        BGPanel.setLayout(BGPanelLayout);
        BGPanelLayout.setHorizontalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        BGPanelLayout.setVerticalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        Center.add(BGPanel);

        javax.swing.GroupLayout BDPanelLayout = new javax.swing.GroupLayout(BDPanel);
        BDPanel.setLayout(BDPanelLayout);
        BDPanelLayout.setHorizontalGroup(
            BDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        BDPanelLayout.setVerticalGroup(
            BDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        Center.add(BDPanel);

        getContentPane().add(Center, java.awt.BorderLayout.CENTER);

        South.setLayout(new java.awt.GridLayout(1, 2));

        AnnulerButton.setText("Annuler");
        AnnulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerButtonActionPerformed(evt);
            }
        });
        South.add(AnnulerButton);

        ValiderButton.setText("Valider");
        ValiderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderButtonActionPerformed(evt);
            }
        });
        South.add(ValiderButton);

        getContentPane().add(South, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerButtonActionPerformed
        this.validated = false;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_AnnulerButtonActionPerformed

    private void ValiderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderButtonActionPerformed
        this.l = new Lot();
        this.l.setDescriptif(DescriptifTF.getText());
        this.l.setNiveau(niveau);
        this.l.setType(type);
        if (type == "Bon cadeau"){
            this.l.setValeur(ValeurCB.getSelectedIndex());
        }
        else{
            this.l.setIcone(icone);
        }
    }//GEN-LAST:event_ValiderButtonActionPerformed

    private void BonCadeauRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BonCadeauRBActionPerformed
        type = "Bon cadeau";
        ValeurCB = new JComboBox();
        
    }//GEN-LAST:event_BonCadeauRBActionPerformed

    private void ObjetRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjetRBActionPerformed
        type = "Objet";
    }//GEN-LAST:event_ObjetRBActionPerformed

    private void Niveau1RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Niveau1RBActionPerformed
        niveau = 1;
    }//GEN-LAST:event_Niveau1RBActionPerformed

    private void Niveau2RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Niveau2RBActionPerformed
        niveau = 2;
    }//GEN-LAST:event_Niveau2RBActionPerformed

    private void Niveau3RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Niveau3RBActionPerformed
        niveau = 3;
    }//GEN-LAST:event_Niveau3RBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnulerButton;
    private javax.swing.JPanel BDPanel;
    private javax.swing.JPanel BGPanel;
    private javax.swing.JRadioButton BonCadeauRB;
    private javax.swing.ButtonGroup CatButtonGroup;
    private javax.swing.JLabel CatLabel;
    private javax.swing.JPanel CatPanel;
    private javax.swing.JPanel Center;
    private javax.swing.JLabel DescriptifLabel;
    private javax.swing.JTextField DescriptifTF;
    private javax.swing.JPanel HDPanel;
    private javax.swing.JPanel HGPanel;
    private javax.swing.JRadioButton Niveau1RB;
    private javax.swing.JRadioButton Niveau2RB;
    private javax.swing.JRadioButton Niveau3RB;
    private javax.swing.ButtonGroup NiveauButtonGroup;
    private javax.swing.JLabel NiveauLabel;
    private javax.swing.JPanel NiveauPanel;
    private javax.swing.JPanel North;
    private javax.swing.JRadioButton ObjetRB;
    private javax.swing.JPanel South;
    private javax.swing.JLabel TitreLabel;
    private javax.swing.JButton ValiderButton;
    // End of variables declaration//GEN-END:variables
}
